#!/bin/sh
# Gleam's warning flag does not reject authored native Erlang warnings.
set -eu
cd "$(dirname "$0")/.."
build_root=$(mktemp -d "${TMPDIR:-/tmp}/llm-wire-native.XXXXXX")
trap 'rm -rf "$build_root"' EXIT HUP INT TERM
if [ "$#" -gt 0 ]; then
  erlc -Werror +warn_unused_vars +warn_unused_function -o "$build_root" "$@"
else
  git ls-files -z -- '*.erl' >"$build_root/sources"
  xargs -0 -r erlc -Werror +warn_unused_vars +warn_unused_function -o "$build_root" <"$build_root/sources"
fi
